[default_config]
version = "0.10.1"
assembler = "gas"
instruction_set = "x86-64"

[default_config.opts]
compiler = "as"
compile_flags_txt = [
    "--fatal-warnings",
    "--warn",
    "--traditional-format",
    "--noexecstack",
    "-gdwarf-2",
    '"-o output.o > /dev/null 2>&1"',
]
diagnostics = true
default_diagnostics = false
